---
title: "Exploratory analysis"
output: github_document
---

```{r}
library(tidyverse)
```


```{r, eval=FALSE}  
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = '90%'
)

theme_set(theme_minimal() + theme(legend.position = 'bottom'))

options(
  ggplot2.continous.colour = 'viridis_d',
  ggplot2.continous.fill = 'viridis_d'
)

scalr_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## load the weather data

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())

weather_df
```

## `group_by`

```{r}
weather_df %>% 
  group_by(name, month)
 #ungroup(name, month)   you can also just ungroup one item
```

## counting things

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n_obs = n())   #this n_obs is just the name you give to the variable
```

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))   ## count how many days in each month
```

we can also use `count()`

```{r}
weather_df %>% 
  count(name, month, name = 'count')
```

A digression on 2X2 tables

```{r}
weather_df %>% 
  filter(name != 'Waikiki_HA') %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ 'cold',
      tmax >= 5 ~ 'not cold',
      TRUE      ~ ''   #in case there are any missing values
    )
  ) %>% 
  group_by(name, cold) %>% 
  summarize(count = n())
```

```{r}
weather_df %>% 
  filter(name != 'Waikiki_HA') %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ 'cold',
      tmax >= 5 ~ 'not cold',
      TRUE      ~ ''   #in case there are any missing values
    )
  ) %>% 
  janitor::tabyl(name, cold)   #this statement is used to create a 2x2 table.
```

## General summaries

You can do lots of summaries.

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),    ##na.rm means get rid of the missing values.
    mean_prcp = mean(prcp, na.rm = TRUE),
    median_tmin = median(tmin, na.rm =TRUE)
  )
```

This is a dataframe! So we can make a plot.

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),    ##na.rm means get rid of the missing values.
    mean_prcp = mean(prcp, na.rm = TRUE),
    median_tmin = median(tmin, na.rm =TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

If you want to summarize many columns at the same time.

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(across(prcp:tmin, mean))
```

Reminder: sometimes your results are easier to read in another format.

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) %>% 
  knitr::kable(digits = 1)
```












